### GEt Account
GET http://localhost:8080/account?user_id=1
Content-Type: application/json

### Create Account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 1234000
}

### Delete Account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000"
}
